# Generated by Django 4.2.7 on 2025-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_assigned_datetime_meeting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='meeting',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
